sudo: false

language: node_js

node_js:
    - "11"
    - "4.2"

branches:
    only:
        - master
        - dev

git:
    depth: 3
    quiet: true

before_script:
    - make setup_cover

script:
    - make node_test

after_script:
    - make send_cover

notifications:
    email: false
